import {
  Brain,
  Target,
  TrendingUp,
  Award,
  ArrowRight,
  CheckCircle2,
  Sparkles,
  Calendar,
  Rocket,
  BadgeCheck,
  Lightbulb,
  AlertCircle,
  ArrowLeft,
} from 'lucide-react';
import type { PageName } from '../types';
import type { CareerAnalysisResult } from '../types/analysis';
import { getAnalysisResult } from '../store/analysisStore';
import { careerAnalysis as fallbackData } from '../data/mockData';
import { Reveal } from '../components/Reveal';
import { Card } from '../components/Card';
import { Badge } from '../components/Badge';
import { ProgressRing } from '../components/ProgressRing';
import { SectionHeading } from '../components/SectionHeading';

interface AnalysisPageProps {
  navigate: (page: PageName) => void;
}

const priorityColors = {
  High: 'error',
  Medium: 'warning',
  Low: 'primary',
} as const;

const difficultyColors = {
  Beginner: 'success',
  Intermediate: 'warning',
  Advanced: 'error',
} as const;

export function AnalysisPage({ navigate }: AnalysisPageProps) {
  // Use AI result if available, otherwise fall back to mock data
  const aiResult: CareerAnalysisResult | null = getAnalysisResult();
  const a = aiResult ?? fallbackData;

  // No AI result and no fallback — shouldn't happen, but handle gracefully
  if (!a) {
    return (
      <div className="pt-32 pb-20 min-h-screen flex items-center justify-center">
        <Card className="p-12 text-center max-w-md">
          <AlertCircle className="w-12 h-12 text-amber-500 mx-auto mb-4" />
          <h2 className="text-xl font-bold text-ink-900 mb-2">No analysis found</h2>
          <p className="text-ink-500 mb-6">Please complete your profile first to generate an AI analysis.</p>
          <button onClick={() => navigate('profile')} className="btn-primary">
            <ArrowLeft className="w-4 h-4" />
            Go to Profile
          </button>
        </Card>
      </div>
    );
  }

  // Determine if we're showing AI or fallback data
  const isAiData = aiResult !== null;
  const topPath = a.careerPaths?.[0];

  return (
    <div className="pt-24 pb-20 min-h-screen bg-gradient-to-b from-primary-50/30 via-white to-white">
      <div className="container-custom">
        {/* Header */}
        <Reveal>
          <div className="text-center mb-12">
            <Badge variant="primary" size="md">
              <Brain className="w-3.5 h-3.5" />
              {isAiData ? 'AI Analysis Complete' : 'Demo Analysis'}
            </Badge>
            <h1 className="mt-4 text-3xl md:text-4xl font-bold text-ink-900">
              Your <span className="gradient-text">Career Analysis</span>
            </h1>
            <p className="mt-3 text-ink-500 text-lg max-w-2xl mx-auto">
              {isAiData
                ? 'Generated by Google Gemini 2.5 Flash based on your unique profile.'
                : 'Showing sample data. Fill out your profile and click "Analyze with AI" for real results.'}
            </p>
          </div>
        </Reveal>

        {/* Top section: Match score + Career Advice summary */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
          {/* Top career match score */}
          <Reveal>
            <Card className="p-8 h-full flex flex-col items-center justify-center text-center bg-gradient-to-br from-primary-50 to-secondary-50 border-primary-100">
              <p className="text-sm font-semibold text-ink-500 uppercase tracking-wider mb-4">
                Top Career Match
              </p>
              <ProgressRing value={topPath?.matchScore ?? 87} size={140} strokeWidth={12} />
              <p className="mt-4 text-lg font-bold text-ink-900">{topPath?.title ?? 'Full-Stack Developer'}</p>
              <Badge variant="success" size="sm">
                <CheckCircle2 className="w-3 h-3" />
                {topPath?.demandLevel ?? 'Growing'} Demand
              </Badge>
            </Card>
          </Reveal>

          {/* Career advice */}
          <Reveal delay={100}>
            <Card className="p-8 lg:col-span-2 h-full">
              <div className="flex items-center gap-2 mb-4">
                <Sparkles className="w-5 h-5 text-primary-500" />
                <h3 className="font-bold text-ink-900">Personalized Career Advice</h3>
              </div>
              <p className="text-ink-600 leading-relaxed">
                {a.careerAdvice}
              </p>
              {topPath && (
                <div className="grid grid-cols-2 gap-4 mt-6">
                  <div className="flex items-center gap-3 p-3 rounded-xl bg-ink-50">
                    <div className="w-10 h-10 rounded-lg bg-primary-100 flex items-center justify-center">
                      <TrendingUp className="w-5 h-5 text-primary-600" />
                    </div>
                    <div>
                      <p className="text-xs text-ink-500">Demand</p>
                      <p className="font-bold text-ink-900">{topPath.demandLevel}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-3 p-3 rounded-xl bg-ink-50">
                    <div className="w-10 h-10 rounded-lg bg-accent-100 flex items-center justify-center">
                      <Award className="w-5 h-5 text-accent-600" />
                    </div>
                    <div>
                      <p className="text-xs text-ink-500">Avg. Salary</p>
                      <p className="font-bold text-ink-900 text-sm">{topPath.averageSalary}</p>
                    </div>
                  </div>
                </div>
              )}
            </Card>
          </Reveal>
        </div>

        {/* Career Recommendations */}
        <Reveal>
          <div className="mb-6">
            <SectionHeading
              eyebrow="Recommendations"
              title="Top 3 Career Paths"
              subtitle="AI-matched career paths ranked by your profile fit."
              center={false}
            />
          </div>
        </Reveal>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          {a.careerPaths.map((path, i) => (
            <Reveal key={i} delay={i * 100}>
              <Card hover className="p-6 h-full">
                <div className="flex items-center justify-between mb-4">
                  <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-primary-500 to-secondary-600 flex items-center justify-center shadow-lg shadow-primary-500/30">
                    <span className="text-white font-bold text-lg">{i + 1}</span>
                  </div>
                  <ProgressRing value={path.matchScore} size={56} strokeWidth={6} />
                </div>
                <h4 className="font-bold text-ink-900 mb-2">{path.title}</h4>
                <p className="text-sm text-ink-500 leading-relaxed mb-4">{path.description}</p>
                <div className="flex flex-wrap gap-2">
                  <Badge variant="success" size="sm">
                    <TrendingUp className="w-3 h-3" />
                    {path.demandLevel}
                  </Badge>
                  <Badge variant="neutral" size="sm">{path.averageSalary}</Badge>
                </div>
              </Card>
            </Reveal>
          ))}
        </div>

        {/* Skill Gap Analysis */}
        <Reveal>
          <Card className="p-8 mb-8">
            <div className="flex items-center gap-2 mb-6">
              <div className="w-10 h-10 rounded-xl bg-primary-50 flex items-center justify-center">
                <Target className="w-5 h-5 text-primary-600" />
              </div>
              <h3 className="font-bold text-ink-900 text-lg">Skill Gap Analysis</h3>
            </div>

            <div className="space-y-5">
              {a.skillGapAnalysis.map((gap, i) => (
                <div key={i} className="grid grid-cols-1 sm:grid-cols-12 gap-3 items-center">
                  <div className="sm:col-span-3">
                    <span className="font-medium text-ink-800 text-sm">{gap.skill}</span>
                  </div>
                  <div className="sm:col-span-2">
                    <Badge variant={priorityColors[gap.priority]} size="sm">
                      {gap.priority} Priority
                    </Badge>
                  </div>
                  <div className="sm:col-span-5">
                    <div className="relative h-6 rounded-full bg-ink-100 overflow-hidden">
                      <div
                        className="absolute top-0 left-0 h-full bg-ink-200 rounded-full"
                        style={{ width: `${gap.requiredLevel}%` }}
                      />
                      <div
                        className="absolute top-0 left-0 h-full bg-gradient-to-r from-primary-500 to-secondary-500 rounded-full transition-all duration-1000"
                        style={{ width: `${gap.currentLevel}%` }}
                      />
                      <div className="absolute inset-0 flex items-center justify-between px-3">
                        <span className="text-xs font-semibold text-white drop-shadow">
                          {gap.currentLevel}%
                        </span>
                        <span className="text-xs font-semibold text-ink-600">
                          Target: {gap.requiredLevel}%
                        </span>
                      </div>
                    </div>
                  </div>
                  <div className="sm:col-span-2 text-right">
                    <span className="text-sm font-bold text-amber-600">Gap: {gap.gap}%</span>
                  </div>
                </div>
              ))}
            </div>

            <div className="flex flex-wrap gap-4 mt-6 pt-4 border-t border-ink-100 text-xs text-ink-500">
              <div className="flex items-center gap-1.5">
                <div className="w-3 h-3 rounded bg-gradient-to-r from-primary-500 to-secondary-500" />
                Your current level
              </div>
              <div className="flex items-center gap-1.5">
                <div className="w-3 h-3 rounded bg-ink-200" />
                Required level
              </div>
            </div>
          </Card>
        </Reveal>

        {/* 30-Day Roadmap */}
        <Reveal>
          <div className="mb-6">
            <SectionHeading
              eyebrow="Short-term Plan"
              title="30-Day Learning Roadmap"
              subtitle="Weekly milestones to kickstart your journey."
              center={false}
            />
          </div>
        </Reveal>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          {a.roadmap30Days.map((item, i) => (
            <Reveal key={i} delay={i * 80}>
              <Card hover className="p-6 h-full">
                <div className="flex items-center gap-2 mb-4">
                  <div className="w-10 h-10 rounded-xl bg-primary-50 flex items-center justify-center">
                    <Calendar className="w-5 h-5 text-primary-600" />
                  </div>
                  <span className="text-xs font-bold text-ink-400 uppercase tracking-wider">
                    Week {i + 1}
                  </span>
                </div>
                <h4 className="font-bold text-ink-900 mb-3">{item.title}</h4>
                <div className="flex flex-wrap gap-1.5 mb-4">
                  {item.skills.map((skill) => (
                    <span key={skill} className="text-xs px-2 py-0.5 rounded-md bg-primary-50 text-primary-700 border border-primary-100">
                      {skill}
                    </span>
                  ))}
                </div>
                <ul className="space-y-1.5">
                  {item.milestones.map((m, mi) => (
                    <li key={mi} className="flex items-start gap-2 text-sm text-ink-600">
                      <CheckCircle2 className="w-4 h-4 text-primary-500 mt-0.5 flex-shrink-0" />
                      {m}
                    </li>
                  ))}
                </ul>
              </Card>
            </Reveal>
          ))}
        </div>

        {/* 90-Day Roadmap */}
        <Reveal>
          <div className="mb-6">
            <SectionHeading
              eyebrow="Mid-term Plan"
              title="90-Day Learning Roadmap"
              subtitle="Monthly milestones to build job-ready proficiency."
              center={false}
            />
          </div>
        </Reveal>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          {a.roadmap90Days.map((item, i) => (
            <Reveal key={i} delay={i * 100}>
              <Card hover className="p-6 h-full">
                <div className="flex items-center gap-2 mb-4">
                  <div className="w-10 h-10 rounded-xl bg-secondary-50 flex items-center justify-center">
                    <Calendar className="w-5 h-5 text-secondary-600" />
                  </div>
                  <span className="text-xs font-bold text-ink-400 uppercase tracking-wider">
                    Month {i + 1}
                  </span>
                </div>
                <h4 className="font-bold text-ink-900 mb-3">{item.title}</h4>
                <div className="flex flex-wrap gap-1.5 mb-4">
                  {item.skills.map((skill) => (
                    <span key={skill} className="text-xs px-2 py-0.5 rounded-md bg-secondary-50 text-secondary-700 border border-secondary-100">
                      {skill}
                    </span>
                  ))}
                </div>
                <ul className="space-y-1.5">
                  {item.milestones.map((m, mi) => (
                    <li key={mi} className="flex items-start gap-2 text-sm text-ink-600">
                      <CheckCircle2 className="w-4 h-4 text-secondary-500 mt-0.5 flex-shrink-0" />
                      {m}
                    </li>
                  ))}
                </ul>
              </Card>
            </Reveal>
          ))}
        </div>

        {/* Projects + Certifications */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
          {/* Recommended Projects */}
          <Reveal>
            <Card className="p-6 h-full">
              <div className="flex items-center gap-2 mb-5">
                <div className="w-10 h-10 rounded-xl bg-accent-50 flex items-center justify-center">
                  <Rocket className="w-5 h-5 text-accent-600" />
                </div>
                <h3 className="font-bold text-ink-900 text-lg">Recommended Projects</h3>
              </div>
              <div className="space-y-4">
                {a.recommendedProjects.map((project, i) => (
                  <div key={i} className="p-4 rounded-xl border border-ink-100 hover:border-primary-200 transition-colors">
                    <div className="flex items-start justify-between mb-2">
                      <h4 className="font-semibold text-ink-800">{project.title}</h4>
                      <Badge variant={difficultyColors[project.difficulty]} size="sm">
                        {project.difficulty}
                      </Badge>
                    </div>
                    <p className="text-sm text-ink-500 leading-relaxed">{project.description}</p>
                  </div>
                ))}
              </div>
            </Card>
          </Reveal>

          {/* Certifications */}
          <Reveal delay={100}>
            <Card className="p-6 h-full">
              <div className="flex items-center gap-2 mb-5">
                <div className="w-10 h-10 rounded-xl bg-primary-50 flex items-center justify-center">
                  <BadgeCheck className="w-5 h-5 text-primary-600" />
                </div>
                <h3 className="font-bold text-ink-900 text-lg">Recommended Certifications</h3>
              </div>
              <div className="space-y-4">
                {a.recommendedCertifications.map((cert, i) => (
                  <div key={i} className="p-4 rounded-xl border border-ink-100 hover:border-primary-200 transition-colors">
                    <h4 className="font-semibold text-ink-800">{cert.name}</h4>
                    <p className="text-sm text-ink-500 mt-1">
                      <span className="font-medium text-ink-700">{cert.provider}</span>
                    </p>
                    <p className="text-sm text-ink-500 mt-1">{cert.relevance}</p>
                  </div>
                ))}
              </div>
            </Card>
          </Reveal>
        </div>

        {/* Final Advice */}
        <Reveal>
          <Card className="p-8 mb-8 bg-gradient-to-br from-primary-50 to-secondary-50 border-primary-100">
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-primary-500 to-secondary-600 flex items-center justify-center flex-shrink-0 shadow-lg shadow-primary-500/30">
                <Lightbulb className="w-6 h-6 text-white" />
              </div>
              <div>
                <h3 className="font-bold text-ink-900 text-lg mb-2">Final Advice from Your AI Mentor</h3>
                <p className="text-ink-600 leading-relaxed">{a.careerAdvice}</p>
              </div>
            </div>
          </Card>
        </Reveal>

        {/* CTA to roadmap */}
        <Reveal>
          <Card className="p-8 lg:p-12 bg-gradient-to-br from-primary-600 to-secondary-700 text-white text-center">
            <h3 className="text-2xl md:text-3xl font-bold mb-3">
              Ready to see your full learning plan?
            </h3>
            <p className="text-primary-50 mb-6 max-w-xl mx-auto">
              Explore the 6-month roadmap with monthly milestones and track your progress.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <button
                onClick={() => navigate('roadmap')}
                className="inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-white text-primary-700 font-bold shadow-xl hover:shadow-2xl hover:-translate-y-0.5 transition-all duration-300"
              >
                View My Roadmap
                <ArrowRight className="w-5 h-5" />
              </button>
              <button
                onClick={() => navigate('profile')}
                className="inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-white/10 text-white font-bold border border-white/20 hover:bg-white/20 transition-all duration-300"
              >
                <ArrowLeft className="w-4 h-4" />
                Update Profile
              </button>
            </div>
          </Card>
        </Reveal>
      </div>
    </div>
  );
}
